name: Nightly Check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:dev
      - run: PROMPTPERFECT_SECRET=$PP SCENEX_SECRET=$SX RATIONALE_SECRET=$RA JINACHAT_SECRET=$CC npm run test:real
        shell: bash
        env:
          PP: ${{ secrets.PROMPTPERFECT_SECRET }}
          SX: ${{ secrets.SCENEX_SECRET }}
          RA: ${{ secrets.RATIONALE_SECRET }}
          CC: ${{ secrets.JINACHAT_SECRET }}
         

